### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by YasogaN** [keifufu/WebNowPlaying-Docs#1]
The CLI item in the [homepage](https://wnp.keifufu.dev/) redirects to a broken link (https://wnp.keifufu.dev/cl/getting-started). it should be pointed to https://wnp.keifufu.dev/cli/getting-started (I'm guessing you missed the [i] in cli when you were typing it out)

**Comment by keifufu** [comment]
Yet again correct, and this time it is indeed a mistake of mine, thanks for pointing that out!

**Comment by YasogaN** [comment]
No problem! Happy to help 😃
